/* ============================================================
   stocks.js  —  종목 데이터 (이 파일만 수정하면 메인에 자동 반영)
   ------------------------------------------------------------
   ▷ 새 종목 추가 방법:
     1) {ticker}_deck.html 파일을 같은 폴더에 생성
     2) 아래 STOCKS 배열 맨 끝에 객체 하나를 추가 (쉼표 주의)
   ▷ 필드 설명:
     ticker     : 티커 (대문자)            예: "NVDA"
     name       : 회사/상품 풀네임          예: "NVIDIA Corporation"
     sector     : 섹터 (아래 SECTORS 중)    예: "반도체"
     marketCap  : 시가총액 (숫자, 단위 = 십억달러 $B)  예: 2650  → $2.65조
     price      : 현재가 (숫자, USD)         예: 276.70
     score      : 투자 매력도 (0~10, 소수 가능)        예: 5.5
     asOf       : 분석 기준일 "YYYY-MM-DD"
     file       : deck 파일명               예: "nvda_deck.html"
     theme      : 카드 액센트 색 (아래 THEMES 키)  예: "fiber"
     tagline    : 한 줄 요약 (카드에 표시)
     flags      : 배지 배열(선택) 예: ["트럼프 픽","엔비디아 픽","레버리지"]
   ※ marketCap 단위는 "십억 달러($B)"로 통일. 예) 1조7500억달러 → 1750
   ============================================================ */

const SECTORS = ["우주항공", "하드웨어", "소프트웨어", "반도체", "ETF", "전기차", "커뮤니케이션", "유통", "소재", "필수소비재", "헬스케어", "소비재", "유틸리티", "산업재", "기타", "에너지", "금융", "부동산"];

const THEMES = {
  rocket: { primary: "#ff5a3c", secondary: "#3ce0ff" },
  steel:  { primary: "#4aa8ff", secondary: "#7cc4ff" },
  azure:  { primary: "#3a8dde", secondary: "#2fd4c4" },
  fiber:  { primary: "#00d9c0", secondary: "#7b6cff" },
  memory: { primary: "#7c5cff", secondary: "#2fd4c4" },
  gold:   { primary: "#e3b24a", secondary: "#ffd277" }
};

const STOCKS = [
  {
    ticker: "SPCX",
    name: "Space Exploration Technologies (SpaceX)",
    sector: "우주항공",
    marketCap: 2550,        // ~$2.55조 = 2550B
    price: 165.78,
    score: 4,
    asOf: "2026-06-24",
    file: "spcx_deck.html",
    theme: "rocket",
    tagline: "사상 최대 IPO 직후 — 사업보다 수급 캘린더가 지배하는 상장 초기 종목",
    flags: ["상장 직후", "오너 리스크"]
  },
  {
    ticker: "DELL",
    name: "Dell Technologies",
    sector: "하드웨어",
    marketCap: 265,         // ~$2,650억 = 265B
    price: 422.86,
    score: 6.5,
    asOf: "2026-06-23",
    file: "dell_deck.html",
    theme: "steel",
    tagline: "AI 데이터센터의 척추 — 실적 폭발 + 트럼프 픽이 겹친 종목",
    flags: ["트럼프 픽"]
  },
  {
    ticker: "MSFT",
    name: "Microsoft Corporation",
    sector: "소프트웨어",
    marketCap: 2620.0,
    price: 352.83,
    score: 7.4,
    asOf: "2026-06-26",
    file: "msft_deck.html",
    theme: "azure",
    tagline: "Azure·Copilot·Office가 묶인 기업 AI의 기본값",
    flags: ["Nasdaq 100 Top 20"]
  },
  {
    ticker: "MRVL",
    name: "Marvell Technology, Inc.",
    sector: "반도체",
    marketCap: 246.05,
    price: 281.26,
    score: 4.9,
    asOf: "2026-06-26",
    file: "mrvl_deck.html",
    theme: "memory",
    tagline: "반도체 관점의 Semiconductors 리더 — 매출 YoY 27.57%, 컨센서스 Strong Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "DRAM",
    name: "Roundhill Memory ETF (+ 2X RAM)",
    sector: "ETF",
    marketCap: 17.46,       // ETF는 시총 아닌 운용자산(AUM) ~$174억. 정렬용 근사치
    price: 76.71,
    score: 6,
    asOf: "2026-06-24",
    file: "dram_ram_deck.html",
    theme: "memory",
    tagline: "AI 메모리 슈퍼사이클 — 역대 최고속 ETF, 한국 메모리 집중 + 2배 레버리지 RAM",
    flags: ["ETF", "레버리지", "환율노출"]
  },
  {
    ticker: "NVDA",
    name: "NVIDIA Corporation",
    sector: "반도체",
    marketCap: 4740.0,
    price: 195.74,
    score: 8.0,
    asOf: "2026-06-26",
    file: "nvda_deck.html",
    theme: "fiber",
    tagline: "AI 가속기의 표준 플랫폼 — 데이터센터 수요와 CUDA 해자가 동시에 작동",
    flags: ["Nasdaq 100 Top 20"]
  },
  {
    ticker: "GOOGL",
    name: "Alphabet Inc.",
    sector: "소프트웨어",
    marketCap: 4190.0,
    price: 343.71,
    score: 7.6,
    asOf: "2026-06-26",
    file: "googl_deck.html",
    theme: "azure",
    tagline: "검색·유튜브·클라우드·TPU를 묶은 AI 복합체",
    flags: ["Nasdaq 100 Top 20"]
  },
  {
    ticker: "GOOG",
    name: "Alphabet Inc. Class C",
    sector: "소프트웨어",
    marketCap: 4190.0,
    price: 336.0,
    score: 7.6,
    asOf: "2026-06-26",
    file: "goog_deck.html",
    theme: "azure",
    tagline: "의결권 없는 Class C로 보는 Alphabet AI·광고·Waymo 옵션",
    flags: ["Nasdaq 100", "Class C"]
  },
  {
    ticker: "AAPL",
    name: "Apple Inc.",
    sector: "하드웨어",
    marketCap: 4040.0,
    price: 275.15,
    score: 6.5,
    asOf: "2026-06-26",
    file: "aapl_deck.html",
    theme: "steel",
    tagline: "프리미엄 디바이스와 서비스 락인의 현금창출 머신",
    flags: ["Nasdaq 100 Top 20"]
  },
  {
    ticker: "AMZN",
    name: "Amazon.com, Inc.",
    sector: "소프트웨어",
    marketCap: 2440.0,
    price: 227.01,
    score: 7.2,
    asOf: "2026-06-26",
    file: "amzn_deck.html",
    theme: "azure",
    tagline: "AWS·광고·물류 효율화가 동시에 이익률을 밀어 올리는 플랫폼",
    flags: ["Nasdaq 100 Top 20"]
  },
  {
    ticker: "AVGO",
    name: "Broadcom Inc.",
    sector: "반도체",
    marketCap: 1800.0,
    price: 378.91,
    score: 7.6,
    asOf: "2026-06-26",
    file: "avgo_deck.html",
    theme: "fiber",
    tagline: "AI 네트워킹·커스텀 ASIC·VMware 현금흐름의 조합",
    flags: ["Nasdaq 100 Top 20"]
  },
  {
    ticker: "TSLA",
    name: "Tesla, Inc.",
    sector: "전기차",
    marketCap: 1410.0,
    price: 375.12,
    score: 4.8,
    asOf: "2026-06-26",
    file: "tsla_deck.html",
    theme: "steel",
    tagline: "전기차보다 자율주행·로봇 기대가 더 비싸게 반영된 종목",
    flags: ["Nasdaq 100 Top 20"]
  },
  {
    ticker: "META",
    name: "Meta Platforms, Inc.",
    sector: "커뮤니케이션",
    marketCap: 1380.0,
    price: 542.87,
    score: 7.5,
    asOf: "2026-06-26",
    file: "meta_deck.html",
    theme: "azure",
    tagline: "AI 추천·광고 효율·Llama 생태계가 수익성을 재가속",
    flags: ["Nasdaq 100 Top 20"]
  },
  {
    ticker: "MU",
    name: "Micron Technology, Inc.",
    sector: "반도체",
    marketCap: 1370.0,
    price: 1213.56,
    score: 6.7,
    asOf: "2026-06-26",
    file: "mu_deck.html",
    theme: "memory",
    tagline: "HBM과 DRAM 업사이클이 만든 초고속 재평가",
    flags: ["Nasdaq 100 Top 20"]
  },
  {
    ticker: "WMT",
    name: "Walmart Inc.",
    sector: "유통",
    marketCap: 921.39,
    price: 115.78,
    score: 5.9,
    asOf: "2026-06-26",
    file: "wmt_deck.html",
    theme: "gold",
    tagline: "방어적 소비와 광고·멤버십 옵션을 가진 초대형 리테일러",
    flags: ["Nasdaq 100 Top 20"]
  },
  {
    ticker: "AMD",
    name: "Advanced Micro Devices, Inc.",
    sector: "반도체",
    marketCap: 868.41,
    price: 532.57,
    score: 6.6,
    asOf: "2026-06-26",
    file: "amd_deck.html",
    theme: "fiber",
    tagline: "GPU 추격자이자 EPYC 서버 CPU의 점유율 확장 스토리",
    flags: ["Nasdaq 100 Top 20"]
  },
  {
    ticker: "ASML",
    name: "ASML Holding N.V.",
    sector: "반도체",
    marketCap: 698.29,
    price: 1841.18,
    score: 5.8,
    asOf: "2026-06-26",
    file: "asml_deck.html",
    theme: "fiber",
    tagline: "EUV 독점력은 강하지만 중국·WFE 사이클 리스크가 따라붙는 장비 최상단",
    flags: ["Nasdaq 100 Top 20"]
  },
  {
    ticker: "INTC",
    name: "Intel Corporation",
    sector: "반도체",
    marketCap: 667.8,
    price: 132.87,
    score: 4.2,
    asOf: "2026-06-26",
    file: "intc_deck.html",
    theme: "memory",
    tagline: "파운드리 턴어라운드 기대가 실적보다 먼저 오른 고위험 재건축",
    flags: ["Nasdaq 100 Top 20"]
  },
  {
    ticker: "AMAT",
    name: "Applied Materials, Inc.",
    sector: "반도체",
    marketCap: 530.36,
    price: 668.0,
    score: 5.7,
    asOf: "2026-06-26",
    file: "amat_deck.html",
    theme: "fiber",
    tagline: "전공정 장비의 넓은 포트폴리오 — AI capex의 후방 수혜",
    flags: ["Nasdaq 100 Top 20"]
  },
  {
    ticker: "LRCX",
    name: "Lam Research Corporation",
    sector: "반도체",
    marketCap: 502.5,
    price: 401.82,
    score: 5.4,
    asOf: "2026-06-26",
    file: "lrcx_deck.html",
    theme: "fiber",
    tagline: "메모리와 선단 공정 투자에 민감한 식각·증착 장비 강자",
    flags: ["Nasdaq 100 Top 20"]
  },
  {
    ticker: "CSCO",
    name: "Cisco Systems, Inc.",
    sector: "하드웨어",
    marketCap: 468.91,
    price: 118.97,
    score: 6.2,
    asOf: "2026-06-26",
    file: "csco_deck.html",
    theme: "steel",
    tagline: "네트워크 장비에서 보안·관측성·AI 이더넷으로 재평가를 노리는 배당 성장주",
    flags: ["Nasdaq 100 Top 20"]
  },
  {
    ticker: "COST",
    name: "Costco Wholesale Corporation",
    sector: "유통",
    marketCap: 417.9,
    price: 942.24,
    score: 6.4,
    asOf: "2026-06-26",
    file: "cost_deck.html",
    theme: "gold",
    tagline: "멤버십 락인과 고회전 식품 트래픽의 프리미엄 방어주",
    flags: ["Nasdaq 100 Top 20"]
  },
  {
    ticker: "ARM",
    name: "Arm Holdings plc",
    sector: "반도체",
    marketCap: 371.38,
    price: 347.71,
    score: 5.0,
    asOf: "2026-06-26",
    file: "arm_deck.html",
    theme: "fiber",
    tagline: "AI 엣지의 설계 로열티 옵션 — 가격은 이미 먼 미래를 본다",
    flags: ["Nasdaq 100 Top 20"]
  },
  {
    ticker: "KLAC",
    name: "KLA Corporation",
    sector: "반도체",
    marketCap: 338.06,
    price: 258.8,
    score: 4.9,
    asOf: "2026-06-26",
    file: "klac_deck.html",
    theme: "fiber",
    tagline: "수율 관리의 필수 장비지만 급등 후 안전마진은 얇아진 상태",
    flags: ["Nasdaq 100 Top 20"]
  },
  {
    ticker: "NFLX",
    name: "Netflix, Inc.",
    sector: "커뮤니케이션",
    marketCap: 298.55,
    price: 70.9,
    score: 6.1,
    asOf: "2026-06-26",
    file: "nflx_deck.html",
    theme: "gold",
    tagline: "글로벌 스트리밍 1위의 광고·라이브·게임 확장 실험",
    flags: ["Nasdaq 100 Top 20"]
  },
  {
    ticker: "TXN",
    name: "Texas Instruments Incorporated",
    sector: "반도체",
    marketCap: 283.78,
    price: 311.81,
    score: 6.0,
    asOf: "2026-06-26",
    file: "txn_deck.html",
    theme: "memory",
    tagline: "반도체 관점의 Semiconductors 리더 — 매출 YoY 18.58%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "PLTR",
    name: "Palantir Technologies Inc.",
    sector: "소프트웨어",
    marketCap: 257.16,
    price: 107.27,
    score: 6.6,
    asOf: "2026-06-26",
    file: "pltr_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Software - Infrastructure 리더 — 매출 YoY 84.71%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "LIN",
    name: "Linde plc",
    sector: "소재",
    marketCap: 241.47,
    price: 522.28,
    score: 5.9,
    asOf: "2026-06-26",
    file: "lin_deck.html",
    theme: "gold",
    tagline: "소재 관점의 Specialty Chemicals 리더 — 매출 YoY 8.25%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "PANW",
    name: "Palo Alto Networks, Inc.",
    sector: "소프트웨어",
    marketCap: 238.87,
    price: 293.09,
    score: 5.6,
    asOf: "2026-06-26",
    file: "panw_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Software - Infrastructure 리더 — 매출 YoY 31.15%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "WDC",
    name: "Western Digital Corporation",
    sector: "하드웨어",
    marketCap: 232.79,
    price: 675.39,
    score: 6.2,
    asOf: "2026-06-26",
    file: "wdc_deck.html",
    theme: "steel",
    tagline: "하드웨어 관점의 Computer Hardware 리더 — 매출 YoY 45.47%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "STX",
    name: "Seagate Technology Holdings plc",
    sector: "하드웨어",
    marketCap: 231.99,
    price: 1025.36,
    score: 5.6,
    asOf: "2026-06-26",
    file: "stx_deck.html",
    theme: "steel",
    tagline: "하드웨어 관점의 Computer Hardware 리더 — 매출 YoY 44.07%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "QCOM",
    name: "QUALCOMM Incorporated",
    sector: "반도체",
    marketCap: 215.96,
    price: 204.9,
    score: 5.6,
    asOf: "2026-06-26",
    file: "qcom_deck.html",
    theme: "memory",
    tagline: "반도체 관점의 Semiconductors 리더 — 매출 YoY -3.46%, 컨센서스 Hold",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "ADI",
    name: "Analog Devices, Inc.",
    sector: "반도체",
    marketCap: 203.57,
    price: 417.93,
    score: 6.9,
    asOf: "2026-06-26",
    file: "adi_deck.html",
    theme: "memory",
    tagline: "반도체 관점의 Semiconductors 리더 — 매출 YoY 37.25%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "TMUS",
    name: "T-Mobile US, Inc.",
    sector: "커뮤니케이션",
    marketCap: 196.5,
    price: 181.57,
    score: 6.4,
    asOf: "2026-06-26",
    file: "tmus_deck.html",
    theme: "azure",
    tagline: "커뮤니케이션 관점의 Telecom Services 리더 — 매출 YoY 10.63%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "PEP",
    name: "PepsiCo, Inc.",
    sector: "필수소비재",
    marketCap: 190.69,
    price: 139.52,
    score: 6.5,
    asOf: "2026-06-26",
    file: "pep_deck.html",
    theme: "gold",
    tagline: "필수소비재 관점의 Beverages - Non-Alcoholic 리더 — 매출 YoY 8.51%, 컨센서스 Hold",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "AMGN",
    name: "Amgen Inc.",
    sector: "헬스케어",
    marketCap: 190.42,
    price: 352.82,
    score: 5.7,
    asOf: "2026-06-26",
    file: "amgn_deck.html",
    theme: "gold",
    tagline: "헬스케어 관점의 Drug Manufacturers - General 리더 — 매출 YoY 5.75%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "CRWD",
    name: "CrowdStrike Holdings, Inc.",
    sector: "소프트웨어",
    marketCap: 172.76,
    price: 678.65,
    score: 6.2,
    asOf: "2026-06-26",
    file: "crwd_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Software - Infrastructure 리더 — 매출 YoY 25.57%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "GILD",
    name: "Gilead Sciences, Inc.",
    sector: "헬스케어",
    marketCap: 153.76,
    price: 123.84,
    score: 7.1,
    asOf: "2026-06-26",
    file: "gild_deck.html",
    theme: "gold",
    tagline: "헬스케어 관점의 Drug Manufacturers - General 리더 — 매출 YoY 4.40%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "APP",
    name: "AppLovin Corporation",
    sector: "커뮤니케이션",
    marketCap: 149.81,
    price: 445.93,
    score: 7.8,
    asOf: "2026-06-26",
    file: "app_deck.html",
    theme: "azure",
    tagline: "커뮤니케이션 관점의 Advertising Agencies 리더 — 매출 YoY 58.97%, 컨센서스 Strong Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "SHOP",
    name: "Shopify Inc.",
    sector: "소프트웨어",
    marketCap: 145.22,
    price: 111.62,
    score: 6.4,
    asOf: "2026-06-26",
    file: "shop_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Software - Application 리더 — 매출 YoY 34.32%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "ISRG",
    name: "Intuitive Surgical, Inc.",
    sector: "헬스케어",
    marketCap: 141.56,
    price: 399.69,
    score: 7.3,
    asOf: "2026-06-26",
    file: "isrg_deck.html",
    theme: "gold",
    tagline: "헬스케어 관점의 Medical Instruments & Supplies 리더 — 매출 YoY 22.96%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "BKNG",
    name: "Booking Holdings Inc.",
    sector: "소비재",
    marketCap: 137.19,
    price: 177.05,
    score: 7.5,
    asOf: "2026-06-26",
    file: "bkng_deck.html",
    theme: "gold",
    tagline: "소비재 관점의 Travel Services 리더 — 매출 YoY 16.17%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "VRTX",
    name: "Vertex Pharmaceuticals Incorporated",
    sector: "헬스케어",
    marketCap: 121.87,
    price: 480.18,
    score: 6.8,
    asOf: "2026-06-26",
    file: "vrtx_deck.html",
    theme: "gold",
    tagline: "헬스케어 관점의 Biotechnology 리더 — 매출 YoY 7.82%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "SBUX",
    name: "Starbucks Corporation",
    sector: "소비재",
    marketCap: 117.57,
    price: 103.16,
    score: 5.9,
    asOf: "2026-06-26",
    file: "sbux_deck.html",
    theme: "gold",
    tagline: "소비재 관점의 Restaurants 리더 — 매출 YoY 8.79%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "FTNT",
    name: "Fortinet, Inc.",
    sector: "소프트웨어",
    marketCap: 109.85,
    price: 149.93,
    score: 6.1,
    asOf: "2026-06-26",
    file: "ftnt_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Software - Infrastructure 리더 — 매출 YoY 20.13%, 컨센서스 Hold",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "PDD",
    name: "PDD Holdings Inc.",
    sector: "소비재",
    marketCap: 104.33,
    price: 73.3,
    score: 6.4,
    asOf: "2026-06-26",
    file: "pdd_deck.html",
    theme: "gold",
    tagline: "소비재 관점의 Internet Retail 리더 — 매출 YoY 11.04%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "CDNS",
    name: "Cadence Design Systems, Inc.",
    sector: "소프트웨어",
    marketCap: 101.56,
    price: 368.23,
    score: 6.5,
    asOf: "2026-06-26",
    file: "cdns_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Software - Application 리더 — 매출 YoY 18.66%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "MAR",
    name: "Marriott International, Inc.",
    sector: "소비재",
    marketCap: 99.91,
    price: 378.91,
    score: 5.6,
    asOf: "2026-06-26",
    file: "mar_deck.html",
    theme: "gold",
    tagline: "소비재 관점의 Lodging 리더 — 매출 YoY 6.24%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "CEG",
    name: "Constellation Energy Corporation",
    sector: "유틸리티",
    marketCap: 95.95,
    price: 268.69,
    score: 7.2,
    asOf: "2026-06-26",
    file: "ceg_deck.html",
    theme: "gold",
    tagline: "유틸리티 관점의 Utilities - Independent Power Producers 리더 — 매출 YoY 63.85%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "MNST",
    name: "Monster Beverage Corporation",
    sector: "필수소비재",
    marketCap: 93.72,
    price: 95.83,
    score: 6.5,
    asOf: "2026-06-26",
    file: "mnst_deck.html",
    theme: "gold",
    tagline: "필수소비재 관점의 Beverages - Non-Alcoholic 리더 — 매출 YoY 26.89%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "CSX",
    name: "CSX Corporation",
    sector: "산업재",
    marketCap: 88.15,
    price: 47.44,
    score: 5.3,
    asOf: "2026-06-26",
    file: "csx_deck.html",
    theme: "steel",
    tagline: "산업재 관점의 Railroads 리더 — 매출 YoY 1.72%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "SNPS",
    name: "Synopsys, Inc.",
    sector: "소프트웨어",
    marketCap: 87.13,
    price: 455.02,
    score: 6.3,
    asOf: "2026-06-26",
    file: "snps_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Software - Infrastructure 리더 — 매출 YoY 41.87%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "ADP",
    name: "Automatic Data Processing, Inc.",
    sector: "소프트웨어",
    marketCap: 86.47,
    price: 216.31,
    score: 6.4,
    asOf: "2026-06-26",
    file: "adp_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Software - Application 리더 — 매출 YoY 6.96%, 컨센서스 Hold",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "ABNB",
    name: "Airbnb, Inc.",
    sector: "소비재",
    marketCap: 84.21,
    price: 141.88,
    score: 6.5,
    asOf: "2026-06-26",
    file: "abnb_deck.html",
    theme: "gold",
    tagline: "소비재 관점의 Travel Services 리더 — 매출 YoY 17.87%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "MELI",
    name: "MercadoLibre, Inc.",
    sector: "소비재",
    marketCap: 82.09,
    price: 1619.25,
    score: 6.6,
    asOf: "2026-06-26",
    file: "meli_deck.html",
    theme: "gold",
    tagline: "소비재 관점의 Internet Retail 리더 — 매출 YoY 49.03%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "CMCSA",
    name: "Comcast Corporation",
    sector: "커뮤니케이션",
    marketCap: 81.05,
    price: 22.69,
    score: 5.8,
    asOf: "2026-06-26",
    file: "cmcsa_deck.html",
    theme: "azure",
    tagline: "커뮤니케이션 관점의 Telecom Services 리더 — 매출 YoY 5.25%, 컨센서스 Hold",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "DDOG",
    name: "Datadog, Inc.",
    sector: "소프트웨어",
    marketCap: 78.65,
    price: 220.94,
    score: 6.6,
    asOf: "2026-06-26",
    file: "ddog_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Software - Application 리더 — 매출 YoY 32.16%, 컨센서스 Strong Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "MDLZ",
    name: "Mondelez International, Inc.",
    sector: "기타",
    marketCap: 78.56,
    price: 61.2,
    score: 6.5,
    asOf: "2026-06-26",
    file: "mdlz_deck.html",
    theme: "gold",
    tagline: "기타 관점의 Confectioners 리더 — 매출 YoY 8.24%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "DASH",
    name: "DoorDash, Inc.",
    sector: "소비재",
    marketCap: 77.08,
    price: 176.91,
    score: 6.0,
    asOf: "2026-06-26",
    file: "dash_deck.html",
    theme: "gold",
    tagline: "소비재 관점의 Internet Retail 리더 — 매출 YoY 33.11%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "ADBE",
    name: "Adobe Inc.",
    sector: "소프트웨어",
    marketCap: 76.88,
    price: 193.41,
    score: 6.8,
    asOf: "2026-06-26",
    file: "adbe_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Software - Application 리더 — 매출 YoY 12.68%, 컨센서스 Hold",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "NXPI",
    name: "NXP Semiconductors N.V.",
    sector: "반도체",
    marketCap: 75.4,
    price: 298.64,
    score: 6.6,
    asOf: "2026-06-26",
    file: "nxpi_deck.html",
    theme: "memory",
    tagline: "반도체 관점의 Semiconductors 리더 — 매출 YoY 12.21%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "AEP",
    name: "American Electric Power Company, Inc.",
    sector: "유틸리티",
    marketCap: 74.54,
    price: 137.0,
    score: 6.0,
    asOf: "2026-06-26",
    file: "aep_deck.html",
    theme: "gold",
    tagline: "유틸리티 관점의 Utilities - Regulated Electric 리더 — 매출 YoY 10.20%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "HON",
    name: "Honeywell International Inc.",
    sector: "산업재",
    marketCap: 73.26,
    price: 231.24,
    score: 5.0,
    asOf: "2026-06-26",
    file: "hon_deck.html",
    theme: "steel",
    tagline: "산업재 관점의 Conglomerates 리더 — 매출 YoY 2.44%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "ORLY",
    name: "O'Reilly Automotive, Inc.",
    sector: "소비재",
    marketCap: 72.02,
    price: 86.9,
    score: 6.9,
    asOf: "2026-06-26",
    file: "orly_deck.html",
    theme: "gold",
    tagline: "소비재 관점의 Auto Parts 리더 — 매출 YoY 10.24%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "MPWR",
    name: "Monolithic Power Systems, Inc.",
    sector: "반도체",
    marketCap: 70.66,
    price: 1438.3,
    score: 7.4,
    asOf: "2026-06-26",
    file: "mpwr_deck.html",
    theme: "memory",
    tagline: "반도체 관점의 Semiconductors 리더 — 매출 YoY 26.14%, 컨센서스 Strong Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "INTU",
    name: "Intuit Inc.",
    sector: "소프트웨어",
    marketCap: 69.77,
    price: 255.07,
    score: 7.1,
    asOf: "2026-06-26",
    file: "intu_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Software - Application 리더 — 매출 YoY 10.37%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "ROST",
    name: "Ross Stores, Inc.",
    sector: "소비재",
    marketCap: 69.01,
    price: 215.13,
    score: 6.9,
    asOf: "2026-06-26",
    file: "rost_deck.html",
    theme: "gold",
    tagline: "소비재 관점의 Apparel Retail 리더 — 매출 YoY 20.57%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "CTAS",
    name: "Cintas Corporation",
    sector: "산업재",
    marketCap: 67.65,
    price: 169.09,
    score: 6.9,
    asOf: "2026-06-26",
    file: "ctas_deck.html",
    theme: "steel",
    tagline: "산업재 관점의 Specialty Business Services 리더 — 매출 YoY 8.90%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "WBD",
    name: "Warner Bros. Discovery, Inc.",
    sector: "커뮤니케이션",
    marketCap: 67.63,
    price: 26.98,
    score: 4.4,
    asOf: "2026-06-26",
    file: "wbd_deck.html",
    theme: "azure",
    tagline: "커뮤니케이션 관점의 Entertainment 리더 — 매출 YoY -0.96%, 컨센서스 Hold",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "PCAR",
    name: "PACCAR Inc",
    sector: "산업재",
    marketCap: 64.04,
    price: 121.68,
    score: 5.0,
    asOf: "2026-06-26",
    file: "pcar_deck.html",
    theme: "steel",
    tagline: "산업재 관점의 Farm & Heavy Construction Machinery 리더 — 매출 YoY -8.94%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "REGN",
    name: "Regeneron Pharmaceuticals, Inc.",
    sector: "헬스케어",
    marketCap: 63.09,
    price: 620.14,
    score: 6.4,
    asOf: "2026-06-26",
    file: "regn_deck.html",
    theme: "gold",
    tagline: "헬스케어 관점의 Biotechnology 리더 — 매출 YoY 19.04%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "BKR",
    name: "Baker Hughes Company",
    sector: "에너지",
    marketCap: 56.49,
    price: 56.94,
    score: 6.8,
    asOf: "2026-06-26",
    file: "bkr_deck.html",
    theme: "gold",
    tagline: "에너지 관점의 Oil & Gas Equipment & Services 리더 — 매출 YoY 2.49%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "FAST",
    name: "Fastenal Company",
    sector: "산업재",
    marketCap: 53.87,
    price: 46.92,
    score: 5.0,
    asOf: "2026-06-26",
    file: "fast_deck.html",
    theme: "steel",
    tagline: "산업재 관점의 Industrial Distribution 리더 — 매출 YoY 12.37%, 컨센서스 Hold",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "FANG",
    name: "Diamondback Energy, Inc.",
    sector: "에너지",
    marketCap: 51.35,
    price: 182.55,
    score: 5.4,
    asOf: "2026-06-26",
    file: "fang_deck.html",
    theme: "gold",
    tagline: "에너지 관점의 Oil & Gas Exploration & Production 리더 — 매출 YoY 4.74%, 컨센서스 Strong Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "EA",
    name: "Electronic Arts Inc.",
    sector: "소프트웨어",
    marketCap: 51.34,
    price: 204.73,
    score: 5.7,
    asOf: "2026-06-26",
    file: "ea_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Electronic Gaming & Multimedia 리더 — 매출 YoY 11.87%, 컨센서스 Hold",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "XEL",
    name: "Xcel Energy Inc.",
    sector: "유틸리티",
    marketCap: 51.03,
    price: 81.75,
    score: 6.0,
    asOf: "2026-06-26",
    file: "xel_deck.html",
    theme: "gold",
    tagline: "유틸리티 관점의 Utilities - Regulated Electric 리더 — 매출 YoY 2.94%, 컨센서스 Strong Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "MCHP",
    name: "Microchip Technology Incorporated",
    sector: "반도체",
    marketCap: 51.02,
    price: 94.12,
    score: 6.3,
    asOf: "2026-06-26",
    file: "mchp_deck.html",
    theme: "memory",
    tagline: "반도체 관점의 Semiconductors 리더 — 매출 YoY 35.11%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "FER",
    name: "Ferrovial N.V.",
    sector: "산업재",
    marketCap: 50.54,
    price: 70.2,
    score: 5.4,
    asOf: "2026-06-26",
    file: "fer_deck.html",
    theme: "steel",
    tagline: "산업재 관점의 Engineering & Construction 리더 — 매출 YoY 5.67%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "EXC",
    name: "Exelon Corporation",
    sector: "유틸리티",
    marketCap: 47.83,
    price: 46.75,
    score: 5.5,
    asOf: "2026-06-26",
    file: "exc_deck.html",
    theme: "gold",
    tagline: "유틸리티 관점의 Utilities - Regulated Electric 리더 — 매출 YoY 7.86%, 컨센서스 Hold",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "ODFL",
    name: "Old Dominion Freight Line, Inc.",
    sector: "산업재",
    marketCap: 45.78,
    price: 220.12,
    score: 4.3,
    asOf: "2026-06-26",
    file: "odfl_deck.html",
    theme: "steel",
    tagline: "산업재 관점의 Trucking 리더 — 매출 YoY -2.92%, 컨센서스 Hold",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "TTWO",
    name: "Take-Two Interactive Software, Inc.",
    sector: "소프트웨어",
    marketCap: 44.32,
    price: 238.72,
    score: 6.2,
    asOf: "2026-06-26",
    file: "ttwo_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Electronic Gaming & Multimedia 리더 — 매출 YoY 6.15%, 컨센서스 Strong Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "KDP",
    name: "Keurig Dr Pepper Inc.",
    sector: "필수소비재",
    marketCap: 44.25,
    price: 32.52,
    score: 5.4,
    asOf: "2026-06-26",
    file: "kdp_deck.html",
    theme: "gold",
    tagline: "필수소비재 관점의 Beverages - Non-Alcoholic 리더 — 매출 YoY 9.38%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "CCEP",
    name: "Coca-Cola Europacific Partners PLC",
    sector: "필수소비재",
    marketCap: 44.21,
    price: 99.6,
    score: 6.4,
    asOf: "2026-06-26",
    file: "ccep_deck.html",
    theme: "gold",
    tagline: "필수소비재 관점의 Beverages - Non-Alcoholic 리더 — 매출 YoY 0.16%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "IDXX",
    name: "IDEXX Laboratories, Inc.",
    sector: "헬스케어",
    marketCap: 43.78,
    price: 554.94,
    score: 6.9,
    asOf: "2026-06-26",
    file: "idxx_deck.html",
    theme: "gold",
    tagline: "헬스케어 관점의 Diagnostics & Research 리더 — 매출 YoY 14.26%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "ADSK",
    name: "Autodesk, Inc.",
    sector: "소프트웨어",
    marketCap: 40.06,
    price: 189.73,
    score: 7.6,
    asOf: "2026-06-26",
    file: "adsk_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Software - Application 리더 — 매출 YoY 18.43%, 컨센서스 Strong Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "ALNY",
    name: "Alnylam Pharmaceuticals, Inc.",
    sector: "헬스케어",
    marketCap: 39.14,
    price: 293.17,
    score: 6.4,
    asOf: "2026-06-26",
    file: "alny_deck.html",
    theme: "gold",
    tagline: "헬스케어 관점의 Biotechnology 리더 — 매출 YoY 96.43%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "PYPL",
    name: "PayPal Holdings, Inc.",
    sector: "금융",
    marketCap: 37.38,
    price: 42.38,
    score: 5.8,
    asOf: "2026-06-26",
    file: "pypl_deck.html",
    theme: "gold",
    tagline: "금융 관점의 Credit Services 리더 — 매출 YoY 7.21%, 컨센서스 Hold",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "AXON",
    name: "Axon Enterprise, Inc.",
    sector: "산업재",
    marketCap: 35.85,
    price: 444.73,
    score: 6.2,
    asOf: "2026-06-26",
    file: "axon_deck.html",
    theme: "steel",
    tagline: "산업재 관점의 Aerospace & Defense 리더 — 매출 YoY 33.75%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "TRI",
    name: "Thomson Reuters Corporation",
    sector: "산업재",
    marketCap: 35.38,
    price: 81.01,
    score: 7.1,
    asOf: "2026-06-26",
    file: "tri_deck.html",
    theme: "steel",
    tagline: "산업재 관점의 Specialty Business Services 리더 — 매출 YoY 9.84%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "PAYX",
    name: "Paychex, Inc.",
    sector: "소프트웨어",
    marketCap: 34.39,
    price: 96.72,
    score: 6.7,
    asOf: "2026-06-26",
    file: "payx_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Software - Application 리더 — 매출 YoY 12.48%, 컨센서스 Hold",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "ROP",
    name: "Roper Technologies, Inc.",
    sector: "소프트웨어",
    marketCap: 33.55,
    price: 332.42,
    score: 7.5,
    asOf: "2026-06-26",
    file: "rop_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Software - Application 리더 — 매출 YoY 11.29%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "MSTR",
    name: "Strategy Inc",
    sector: "소프트웨어",
    marketCap: 30.0,
    price: 85.33,
    score: 6.4,
    asOf: "2026-06-26",
    file: "mstr_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Software - Application 리더 — 매출 YoY 11.92%, 컨센서스 Strong Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "GEHC",
    name: "GE HealthCare Technologies Inc.",
    sector: "헬스케어",
    marketCap: 29.54,
    price: 64.94,
    score: 6.1,
    asOf: "2026-06-26",
    file: "gehc_deck.html",
    theme: "gold",
    tagline: "헬스케어 관점의 Medical Devices 리더 — 매출 YoY 7.41%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "WDAY",
    name: "Workday, Inc.",
    sector: "소프트웨어",
    marketCap: 28.1,
    price: 113.77,
    score: 7.2,
    asOf: "2026-06-26",
    file: "wday_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Software - Application 리더 — 매출 YoY 13.48%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "KHC",
    name: "The Kraft Heinz Company",
    sector: "필수소비재",
    marketCap: 27.83,
    price: 23.47,
    score: 5.2,
    asOf: "2026-06-26",
    file: "khc_deck.html",
    theme: "gold",
    tagline: "필수소비재 관점의 Packaged Foods 리더 — 매출 YoY 0.80%, 컨센서스 Hold",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "CPRT",
    name: "Copart, Inc.",
    sector: "산업재",
    marketCap: 27.82,
    price: 30.05,
    score: 6.5,
    asOf: "2026-06-26",
    file: "cprt_deck.html",
    theme: "steel",
    tagline: "산업재 관점의 Specialty Business Services 리더 — 매출 YoY 2.09%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "DXCM",
    name: "DexCom, Inc.",
    sector: "헬스케어",
    marketCap: 26.49,
    price: 68.65,
    score: 7.6,
    asOf: "2026-06-26",
    file: "dxcm_deck.html",
    theme: "gold",
    tagline: "헬스케어 관점의 Medical Devices 리더 — 매출 YoY 15.05%, 컨센서스 Strong Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "VRSK",
    name: "Verisk Analytics, Inc.",
    sector: "산업재",
    marketCap: 23.2,
    price: 177.04,
    score: 6.3,
    asOf: "2026-06-26",
    file: "vrsk_deck.html",
    theme: "steel",
    tagline: "산업재 관점의 Consulting Services 리더 — 매출 YoY 3.93%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "INSM",
    name: "Insmed Incorporated",
    sector: "헬스케어",
    marketCap: 22.64,
    price: 104.47,
    score: 6.5,
    asOf: "2026-06-26",
    file: "insm_deck.html",
    theme: "gold",
    tagline: "헬스케어 관점의 Biotechnology 리더 — 매출 YoY 229.62%, 컨센서스 Strong Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "ZS",
    name: "Zscaler, Inc.",
    sector: "소프트웨어",
    marketCap: 20.02,
    price: 123.8,
    score: 7.1,
    asOf: "2026-06-26",
    file: "zs_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Software - Infrastructure 리더 — 매출 YoY 25.43%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "TEAM",
    name: "Atlassian Corporation",
    sector: "소프트웨어",
    marketCap: 18.95,
    price: 74.68,
    score: 7.1,
    asOf: "2026-06-26",
    file: "team_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Software - Application 리더 — 매출 YoY 31.71%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "CTSH",
    name: "Cognizant Technology Solutions Corporation",
    sector: "소프트웨어",
    marketCap: 18.55,
    price: 39.15,
    score: 6.5,
    asOf: "2026-06-26",
    file: "ctsh_deck.html",
    theme: "azure",
    tagline: "소프트웨어 관점의 Information Technology Services 리더 — 매출 YoY 5.83%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "CHTR",
    name: "Charter Communications, Inc.",
    sector: "커뮤니케이션",
    marketCap: 17.96,
    price: 129.65,
    score: 5.6,
    asOf: "2026-06-26",
    file: "chtr_deck.html",
    theme: "azure",
    tagline: "커뮤니케이션 관점의 Telecom Services 리더 — 매출 YoY -1.00%, 컨센서스 Hold",
    flags: ["Nasdaq 100", "잔여 80"]
  },
  {
    ticker: "CSGP",
    name: "CoStar Group, Inc.",
    sector: "부동산",
    marketCap: 11.7,
    price: 28.64,
    score: 6.0,
    asOf: "2026-06-26",
    file: "csgp_deck.html",
    theme: "gold",
    tagline: "부동산 관점의 Real Estate Services 리더 — 매출 YoY 22.54%, 컨센서스 Buy",
    flags: ["Nasdaq 100", "잔여 80"]
  }

];

/* marketCap 표기 헬퍼: 십억달러($B) → 사람이 읽는 문자열 */
function fmtMarketCap(b) {
  if (b == null || isNaN(b)) return "—";
  if (b >= 1000) return "$" + (b / 1000).toFixed(2).replace(/\.?0+$/, "") + "조";
  return "$" + b.toFixed(0) + "B";
}
